export default {
    START_FILMS_REQUEST: 1,
    FINISH_FILMS_REQUEST: 2,
    CHANGE_SEARCH_STRING: 3,
    FINISH_CERTAIN_FILM_REQUEST: 4,
    START_VIDEO_REQUEST: 5,
    FINISH_VIDEO_REQUEST: 6,
    TOGGLE_AUTH_DIALOG: 7,
    AUTHORIZATION: 8,
    SIGN_OUT: 9,
    FINISH_FAVORITES_REQUEST: 10,
    ADD_TO_FAVORITE: 11,
    REMOVE_FROM_FAVORITE: 12,
    FAV_CHECKING: 13,
    FINISH_FAV_CHEKING: 14,
    ERROR: 15
}