export default {
    START_FILMS_REQUEST: 1,
    FINISH_FILMS_REQUEST: 2,
    CHANGE_SEARCH_STRING: 3,
    FINISH_CERTAIN_FILM_REQUEST: 4,
    START_VIDEO_REQUEST: 5,
    FINISH_VIDEO_REQUEST: 6,
    TOGGLE_AUTH_DIALOG: 7,
    AUTHORIZATION: 8,
    SIGN_OUT: 9
}